### ISSUE TITLE
Expo Requests upgrade before eject so eject fails

### ISSUE THREAD

**Issue by markTree** [bitrise-steplib/steps-expo-detach#11]
Trying to eject expo app and the step fails with the following: 

Eject project
$ expo "eject" "--non-interactive" "--eject-method" "expoKit"
- Making sure project is set up correctly...
[21:43:46] Input is required, but Expo CLI is in non-interactive mode.
Required input:
> We recommend upgrading to the latest SDK version before ejecting. SDK 37 introduces support for OTA updates and notifications in ejected projects, and includes many features that make ejecting your project easier. Would you like to continue ejecting anyways?
Failed to eject project: exit status 1

I tried upgrading but it says no version 37 is available.

**Comment by bitce** [comment]
Hi @markTree! Can you please include a build URL where this issue is happening?

**Comment by LazyKeru** [comment]
Running  a script in workflow, with :
`expo upgrade
expo install expo-updates`
Seemed to fix the problem for me
