### ISSUE TITLE
error: unknown option `--eject-method'

### ISSUE THREAD

**Issue by jeremyalan** [bitrise-steplib/steps-expo-detach#12]
The latest release of `expo-cli` removes the `--eject-method` option, which causes this step to fail.

According to NPM, the breaking change was pushed on (or around) Oct 14, 2020.  Quick fix is to explicitly set the `expo-cli` version to 3.27.14, which is the latest version of the package that supports this flag.

**Comment by bitce** [comment]
Thanks for bringing this to our attention @jeremyalan! We're definitely taking a look.

**Comment by KLaci** [comment]
Any update on this issue?

**Comment by bitce** [comment]
Hi @KLaci - there is no update on this just yet unfortunately, for now please opt for the workaround.
