### ISSUE TITLE
post-compilation simple expo 0.40.0 app crash on android "expo-updates must be configured with a valid update URL or scope key"

### ISSUE THREAD

**Issue by allan-simon** [bitrise-steplib/steps-expo-detach#14]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? _1.0.0_
- Is the issue reproducible with the latest version? _YES _
- Does the issue happen sporadically, or every time? _ EVERY TIME_
- Is the issue reproducible locally by following our [local debug guide](NO)? _ NO _

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

When building on btirise ,  this steps does not generate a EXPO_UPDATE_URL in the manifest of android
which cause the app to crash at runtime with the following error in `logcat`
```
expo-updates must be configured with a valid update URL or scope key
```

analyzing the produce apk confirm this hypothesis (no EXPO_UPDATE_URL in manifest) 

however when building locally with bitrise cli,  this variable is present, and the apk is then able to launch the app correctly 

### Bitrise info

- Build URL: https://app.bitrise.io/build/7412ee4d68eaeffc#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES_
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

Create a managed app with expo-cli , for sdk 40 of expo, nothing more 

1. ...
2. ...

**Comment by allan-simon** [comment]
is it because locally I have run `expo login`  some times ago ?

**Comment by allan-simon** [comment]
I confirm that by adding a shell step before, where i install and do `expo login` manually,  the variable is not present in the manifest

**Comment by bitce** [comment]
Hi @allan-simon! Sorry for the delay, but thanks a lot for a detailed report! We've created an item for our backlog to fix this, will be reaching out to you once we have some progress on that.

**Comment by adborbas** [comment]
Hi @allan-simon,

According to [Installing expo-updates](https://docs.expo.io/bare/installing-updates/#installation):
> Once installation is complete, apply the changes from the following diffs to configure expo-updates in your project.

and [here](https://docs.expo.io/bare/installing-updates/#configuration-for-android) are the changes required for Android.

Based on the above, I would expect that the source should contain the EXPO_UPDATE_URL in the manifest. Could you please confirm that you have committed all your changes to Git before running the workflow?

Thanks,
Adam

**Comment by allan-simon** [comment]
note that:
  *  I didn't install expo-updates myself, (it is there as per the managed workflow) 
  *  I don't have a manifest at all in my git because i'm using the managed workflow and the ejection is done during the bitrise CI

**Comment by adborbas** [comment]
Sure, @allan-simon that makes sense. 

I have created a repro app on Bitrise and can confirm that ejecting does break the apk. On the other hand, I have also applied the workaround you have mentioned, installing expo and running `expo login` from a script. This way, the required field is present in the manifest file in my case. 

I'm yet to confirm whether the resulting .apk is valid and the application is not crashing. I'll get back to you.

**Comment by adborbas** [comment]
The app start with your suggested workaround. Could you please confirm that installing expo and running expo login from a script step produces a valid apk?

You can also refer to [this](https://app.bitrise.io/build/392a731e74723916#?tab=log) build for more info on how the repro app is set up.

**Comment by allan-simon** [comment]
@adborbas  yes i confirm you that, your repro build looks like what i had :+1:

**Comment by adborbas** [comment]
Hi @allan-simon ,

With the new [1.1.0 release](https://github.com/bitrise-steplib/steps-expo-detach/releases/1.1.0) you can provide your Expo account's username and password to the Step and it will log you in before ejecting the project. 

I'll lock this issue but please feel free to open a new one if the issue reoccurs.
