### ISSUE TITLE
[React Native + Expo] Getting build failures

### ISSUE THREAD

**Issue by luanccp** [bitrise-steplib/steps-expo-detach#6]
URL: https://app.bitrise.io/build/133aeab930c518d0

### app.json
```json
{
  "expo": {
    "name": "ChronosApp",
    "description": "Alpha-release",
    "slug": "Chronos-app",
    "privacy": "public",
    "sdkVersion": "32.0.0",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "packagerOpts": {
      "assetExts": ["ttf", "mp4"]
    },
    "android": {
      "package": "com.chronos.chronosapp"
    },
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.chronos.chronosapp"
    },
    "platforms": [
      "android",
      "ios"
    ]
  },
  "name": "ChronosApp",
  "displayName": "Chronos App"
}
```
### package.json
```json
{
  "main": "node_modules/expo/AppEntry.js",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^32.0.0",
    "firebase": "^6.0.4",
    "moment": "^2.24.0",
    "native-base": "2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-native-chart-kit": "^3.0.1",
    "react-native-elements": "^1.1.0",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "3.0.0",
    "styled-components": "^4.3.1"
  },
  "devDependencies": {
    "babel-preset-expo": "^5.0.0"
  }
}

```

**Comment by bitce** [comment]
Hi @luanccp!

Please make sure you are providing either "bare" or "expokit" as the eject-method.

**Comment by luanccp** [comment]
I had to set my expo login and password in the workflow.
That fix the expo issue, but now I've got this:
`android-build@0.10.0 (exit code: 1)`

**Comment by luanccp** [comment]
[f2adf890f1dda863 (1).log](https://github.com/bitrise-steplib/steps-expo-detach/files/3443412/f2adf890f1dda863.1.log)

**Comment by ghost** [comment]
Hi @luanccp, the build log you sent me in your most recent post still appears to show an issue with the steps-expo-detach step. Could you please make sure you're sending me the one with the error in the android-build step? Thanks! 😄

**Comment by cjke** [comment]
> Please make sure you are providing either "bare" or "expokit" as the eject-method.

@bitce How/where does one do this?

**Comment by bitce** [comment]
Hi @cjke,

Ideally you provide your Expo account credentials to the step, and that will result in the regular Expokit method 🙂

**Comment by cjke** [comment]
Thanks @bitce !

Sorry my last message came off a little cold - I'd been struggling to get something setup end to end and felt like I was hitting a lot of deadends, but I appreciate your help (and off in the forums)
